Repository manoj8260/UrbanBoard, pull requests merged in 2025-07, with the labels that each got.

#6 fixed bug in pg form
  dashboard/views.py
Labels: bug

#8 account activation
  UrbanBoard/settings.py
  accounts/emails.py
  accounts/forms.py
  accounts/templates/accounts/account_activate.html
  accounts/templates/accounts/activation_pending.html
  accounts/urls.py
  accounts/views.py
Labels: enhancement

#9 #Features/forget password
  UrbanBoard/settings.py
  accounts/templates/accounts/signin.html
  accounts/templates/email/password_reset.html
  accounts/templates/email/password_reset_complete.html
  accounts/templates/email/password_reset_confirm.html
  accounts/templates/email/password_reset_done.html
  accounts/templates/email/password_reset_email.html
  accounts/templates/email/password_reset_invalid.html
  accounts/urls.py
  accounts/views.py
Labels: documentation

#13 Book Now complete , Booking Requests for landlord pending
  dashboard/admin.py
  dashboard/templates/dashboard/boarder_home.html
  dashboard/templates/dashboard/booking_successful.html
  dashboard/urls.py
  dashboard/views.py
  media/flat_images/wallpaperflare.com_wallpaper1.jpg
  urbanstay/migrations/0002_booking.py
  urbanstay/models.py
Labels: enhancement

#16 fixed error rising for existing user during google login
  UrbanBoard/settings.py
  accounts/pipeline.py
Labels: bug fixed

#17 #manoj
  UrbanBoard/settings.py
  accounts/backends.py
  accounts/emails.py
  accounts/pipeline.py
  accounts/templates/accounts/home.html
  accounts/urls.py
  accounts/views.py
Labels: bug fixed
